### ISSUE TITLE
Option to provide built executable

### ISSUE THREAD

**Issue by ghost** [Neolex-Security/WaybackRust#1]
Yet to use it but looks great.

Could you provide a prebuilt executable to just download and use?

**Comment by Neolex-Security** [comment]
Hello,
I just added a statically linked binary for version 0.1.3 on [releases](https://github.com/Neolex-Security/WaybackRust/releases) 
I hope it will work for you, It does work on my debian and on a ubuntu docker after installing libssl (should be already installed if you have curl for example)
