### ISSUE TITLE
Delay

### ISSUE THREAD

**Issue by Sh1Yo** [Neolex-Security/WaybackRust#2]
Sometimes domains has a protection against brutforce and when waybackrust tries to check url, domain send error "too many requests" even with 1 thread

**Comment by Neolex-Security** [comment]
What do you think I should do ? 
I think you should use  the flag to not check urls status.

**Comment by Neolex-Security** [comment]
The delay option is added in the v0.1.7 @Sh1Yo ! 
I hope it working as you want.
