### ISSUE TITLE
Windows exe

### ISSUE THREAD

**Issue by copy-and-paste** [Neolex-Security/WaybackRust#5]
Add a release for windows in exe format

**Comment by Neolex-Security** [comment]
I have problem for cross compilation from Linux to Windows but I'll try to do it when I'll have some time to.

**Comment by Neolex-Security** [comment]
@copy-and-paste Hi , I added a exe binary in the release.
Can you confirm me that it works on your machine ?

**Comment by copy-and-paste** [comment]
Works...ty
