### ISSUE TITLE
[Error] Crash when using the --threads argument.

### ISSUE THREAD

**Issue by s7x** [Neolex-Security/WaybackRust#6]
Hello there,

### Information

- Cargo version: 1.66.1 (ad779e08b 2023-01-10)
- OS: Arch 6.4.1-arch2-1 
- WaybackRust version: waybackrust 0.2.11
  - Downloaded from git then used cargo build --release

There's a crash when using the **urls** subcommand with the **--threads** argument:

```
thread 'main' panicked at 'Mismatch between definition and access of `threads`. Could not downcast to TypeId { t: 10522819541147869382 }, need to downcast to TypeId { t: 6214212203280860907 }
', /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.3.11/src/parser/error.rs:32:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Command used

```
waybackrust urls -t 4 example.com
```

Cheers!

**Comment by Neolex-Security** [comment]
Hello @s7x ,
Sorry for the delay I didnt get the notification and didn't see it
I Just fixed this error now !

**Comment by s7x** [comment]
Thanks a lot!
